{% set version = "1.6.0" %}

package:
  name: perf
  version: {{ version }}

source:
  url: https://github.com/vstinner/pyperf/archive/{{ version }}.tar.gz
  sha256: 7af7b9cfd9d26548ab7127f8e51791357ecd78cda46aad5b2d9664a70fc58878

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyperf = perf.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - statistics  # [py2k]

test:
  imports:
    - perf
  commands:
    - pyperf --help

about:
  home: https://github.com/vstinner/pyperf
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: "Toolkit to run Python benchmarks"
  doc_url: https://pyperf.readthedocs.io/en/latest/
  dev_url: https://github.com/vstinner/pyperf

extra:
  recipe-maintainers:
    - dougalsutherland
