{% set name = "perf" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7fd3a9a174a17ca36de63563f394eaafc7d4ce11fd3ae7c28d4c38cf6403bef

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyperf = perf.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - statistics  # [py2k]

test:
  imports:
    - perf
  commands:
    - pyperf --help

about:
  home: http://github.com/vstinner/perf/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Toolkit to run Python benchmarks'
  doc_url: http://perf.readthedocs.io/
  dev_url: https://github.com/vstinner/perf/

extra:
  recipe-maintainers:
    - dougalsutherland
