travis:
  secure:
    BINSTAR_TOKEN: YIvMf8U8gZZW7dqhlSyEJKVZaNcuCTsumpV/x0bRdJlR1EIEyW3zW7wmHJxpiUUbZ1aMvDA9M6pWbniiQNqYqPIGCn+bwcCYGt7h7f7ytAB+5kTlUSUeo5+KX5ydIyu8GN/ZeUyxxQN2SWfvtcL3NDphSWGFLn8yRAbWrkrw/Nd1BzJd/qCiPID7lngnfPHiPiaU6KfQH7IBe9NaB0SxFTNMCGDP2JpOPLRAeQkggNvpDBhYzF+VLIasRXsvq2lITyEV4o7fBBzb+NCkFVQHQ1+wl9EEXyij+mjGK3j2ee4mCJBJUiAGE0/21moL2+wrlK4mqNkNlvltMMwGLhH3ZmiNAU4dHmF7fBrqmfQRyKBk2acrzkGlF85EGBhUk6ijO9JcM8567n14ojAjaEd2bdstaFoTJHGm1uriI1gp+278wM4FnJYXpNIKnDs8R+B7qgk1m0YiXGaRl0G270OmUH9qrzJpWkQ1mDfG7S/TdROFldQhXATGsh9wAvTwF9Lcqe+6jkwBotpaKPKAdENR8FA2v1iPwLxtrRZ8NtfXmKyBJLNwrbA94KCAUVSNMNQHXWd2pJWQpwxssQa76u2pTDHvlfQdWeLFEXULTHZOX3+Ioos+H+PIQfoaDc0EC9JkSs3dosKoiaXesFZFTtfLf3B8PtZEpyELXWIyOrueKLs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
